name: "Bug"
description: Hata raporu ve yeniden uretim adimlari
title: "[Bug] "
labels:
  - "type:bug"
  - "todo"
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Kisa ozet, hangi kullanici/ortam etkilendi?
      placeholder: "Ornek: Prod login sayfasi, Chrome"
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Adimlar ve test datasi
      placeholder: |
        1. ...
        2. ...
        Expected:
        Actual:
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Hata giderildi saymak icin ne gerekli?
      placeholder: |
        - ...
  - type: input
    id: scope
    attributes:
      label: Scope tags
      description: @ui, @api, ya da her ikisi
      placeholder: "@ui"
  - type: textarea
    id: artifacts
    attributes:
      label: Logs / artifacts
      description: Trace, screenshot, ilgili test komutu ve cikti
      placeholder: |
        Command: npx playwright test --grep @ui
        Artifacts: <link>
