name: "\U0001F41B Bug"
description: Hata raporu ve yeniden üretim adımları
title: "[Bug] "
labels:
  - "type:bug"
  - "todo"
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Kısa özet, hangi kullanıcı/ortam etkilendi?
      placeholder: Örn. Prod login sayfası, chrome
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Adımlar ve test datası
      placeholder: |
        1. ...
        2. ...
        Expected:
        Actual:
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Hata giderildi saymak için ne gerekli?
      placeholder: |
        - ...
  - type: input
    id: scope
    attributes:
      label: Scope tags
      description: @ui, @api, ya da her ikisi
      placeholder: "@ui"
  - type: textarea
    id: artifacts
    attributes:
      label: Logs / artifacts
      description: Trace, screenshot, ilgili test komutu ve çıktı
      placeholder: |
        Command: npx playwright test --grep @ui
        Artifacts: <link>
