name: "Feature/Task"
description: Yeni test senaryosu veya is gorevi
title: "[Task] "
labels:
  - "type:task"
  - "todo"
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Kapsam, motivasyon, ilgili dokuman/link
      placeholder: "Ornek: Login smoke genisletme, Figma linki"
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bitti sayilmasi icin gereken kosullar
      placeholder: |
        - ...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps / Test data
      description: Planlanan adimlar, veri setleri, mock ihtiyaclari
  - type: input
    id: scope
    attributes:
      label: Scope tags
      description: @ui, @api, ya da her ikisi
      placeholder: "@api"
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Riskler, bagimliliklar, hedef surum
